--- #YAML:1.0
name:                Acme-AGMorse
version:             0.03
abstract:            Perl extension for compiling and sending Morse code      
license:             ~
author:              
    - paula <paula@>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Audio::Beep:                   0.11
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
